import Image from 'next/image';
import styles from "../styles/Home.module.css";
import Banner from "../../public/assets/banner.png";
import { useState } from "react";
import {
  filterProdukte,
  suchtProdukt,
  produkteVorspeise,
} from "../service";
import Head from 'next/head'
import Karten from '../components/karten'
import Kategorien from '../components/kategorien'
import SuchtLeiste from '../components/suchtleiste'


export default function Home() {

  const [gefiltertDaten, setgefiltertDaten] = useState(produkteVorspeise);
  const [textSuchtGetippt, setTextSuchtGetippt] = useState("");

  const [knopftGetippt, setKnopfGetippt] = useState("Vorspeise");

  const griffSucht = (textGetippt) => {
    setTextSuchtGetippt(textGetippt);
    textGetippt.length >= 3 && setgefiltertDaten(suchtProdukt(textGetippt));
    setKnopfGetippt("");
  };

  const griffFilter = (kategorie) => {
    setTextSuchtGetippt("");
    setgefiltertDaten(filterProdukte(kategorie));
    setKnopfGetippt(kategorie);
  };

  return (
    <>
      <Head>
        <title>RESTAURANT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
      </Head>
      <header className={styles.banner}>
        <Image src={Banner} alt="banner" />
        <div>
          <h1>RESTAURANT</h1>
          <p>
          Von klassischen Gerichten bis hin zu überraschenden Kreationen ist unsere Speisekarte ein
          Verfeinerung raffinierter Aromen.
          </p>
        </div>
      </header>
      <main className={styles.container_haupt}>
        <Kategorien
          griffFilter={griffFilter}
          knopftGetippt={knopftGetippt}
        />

        <SuchtLeiste
          textSuchtGetippt={textSuchtGetippt}
          griffSucht={griffSucht}
        />

        <section className={styles.section_karten}>
          <div>
            <h2>Speisecarte</h2>
          </div>

          <div className={styles.container_karten}>
            {gefiltertDaten.map((produkt) => (
              <Karten key={produkt.id} produkt={produkt} />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}